# Generated by Django 2.2.1 on 2020-10-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=25)),
                ('Surname', models.CharField(max_length=50)),
                ('LastName', models.CharField(blank=True, max_length=50)),
                ('Birthday', models.DateField(blank=True)),
                ('Gender', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите жанр книги', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=13, verbose_name='ISBN')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('YearEdition', models.DateField(blank=True)),
                ('author', models.ManyToManyField(to='catalog.Author')),
                ('genre', models.ManyToManyField(to='catalog.Genre')),
            ],
        ),
    ]
