# Generated by Django 2.2.1 on 2020-10-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='Birthday',
            field=models.DateField(),
        ),
    ]
