# Generated by Django 2.2.1 on 2020-10-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20201024_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='Birthday',
            field=models.DateField(blank=True),
        ),
    ]
