# Generated by Django 2.2.1 on 2020-10-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20201025_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='Birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
